<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>gecko</groupId>
    <artifactId>gecko-parent</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <name>GeckoCIRCUITS Parent</name>
    <description>Parent POM and Aggregator for all GeckoCIRCUITS modules</description>
    <url>https://github.com/geckocircuits</url>

    <modules>
        <module>src/modules/gecko-simulation-core</module>
        <module>src/modules/gecko-gui</module>
        <module>src/modules/gecko-rest-api</module>
    </modules>
</project>
