package gecko.mcp;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Byte-exact equivalence tests against .ipes outputs generated by the
 * original Python generators (scripts/desktop/extract-templates.py). This is
 * the guard that keeps the Java port faithful.
 */
class ProjectGoldenTest {

    private static String golden(String name) throws IOException {
        try (InputStream in = ProjectGoldenTest.class.getResourceAsStream("/golden/" + name)) {
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    @Test
    void pfcMatchesPythonDefaults() throws IOException {
        assertEquals(golden("pfc_0.ipes"), PfcProject.generateIpesText(PfcProject.Params.defaults()));
    }

    @Test
    void pfcMatchesPythonVariedParameterSets() throws IOException {
        assertEquals(golden("pfc_1.ipes"), PfcProject.generateIpesText(
                new PfcProject.Params(60.0, 24.0, 50.0, 25000.0, 0.0008, 0.0068,
                        25.0, 25.0, 0.05, 0.10, 1e-6)));
        assertEquals(golden("pfc_2.ipes"), PfcProject.generateIpesText(
                new PfcProject.Params(50.0, 30.0, 50.0, 20000.0, 0.001, 0.0047,
                        25.0, 25.0, 0.05, 0.10, 1e-6)));
        assertEquals(golden("pfc_3.ipes"), PfcProject.generateIpesText(
                new PfcProject.Params(50.0, 24.0, 50.0, 20000.0, 0.0008, 0.0068,
                        12.5, 50.0, 0.06, 0.10, 1e-6)));
        assertEquals(golden("pfc_4.ipes"), PfcProject.generateIpesText(
                new PfcProject.Params(50.0, 24.0, 60.0, 20000.0, 0.0008, 0.0068,
                        25.0, 25.0, 0.05, 0.05, 2e-6)));
    }

    @Test
    void llcMatchesPythonDefaults() throws IOException {
        assertEquals(golden("llc_0.ipes"), LlcProject.generateIpesText(LlcProject.Params.defaults()));
    }

    @Test
    void llcMatchesPythonVariedParameterSets() throws IOException {
        assertEquals(golden("llc_1.ipes"), LlcProject.generateIpesText(
                new LlcProject.Params(300.0, 48.0, 2000.0, 100000.0, 2.2e-6, 1.15e-6,
                        1.1e-5, 1.8e-7, null, null, 0.0003, 2e-8, 0.002, 1.5e-9)));
        assertEquals(golden("llc_2.ipes"), LlcProject.generateIpesText(
                new LlcProject.Params(400.0, 200.0, 10000.0, 250000.0, 1.0e-6, 2.0e-6,
                        1.1e-5, 1.8e-7, null, null, 0.0003, 2e-8, 0.002, 1.5e-9)));
        assertEquals(golden("llc_3.ipes"), LlcProject.generateIpesText(
                new LlcProject.Params(400.0, 200.0, 10000.0, 100000.0, 2.2e-6, 1.15e-6,
                        2.2e-5, 2.5e-7, null, null, 0.0003, 2e-8, 0.002, 1.5e-9)));
        assertEquals(golden("llc_4.ipes"), LlcProject.generateIpesText(
                new LlcProject.Params(400.0, 24.0, 500.0, 100000.0, 2.2e-6, 1.15e-6,
                        1.1e-5, 1.8e-7, null, null, 0.0003, 2e-8, 0.002, 1.5e-9)));
    }
}
